package memory

import (
	"reflect"
	"strings"
	"testing"
	"unicode/utf8"
)

// TestTruncationRuneSafe: long umlaut texts must not be cut in the middle of a
// rune (otherwise invalid UTF-8 ends up in the prompt/title).
func TestTruncationRuneSafe(t *testing.T) {
	long := strings.Repeat("ä", 900) // 900 runes = 1800 bytes
	if got := FormatForPrompt([]Entry{{Title: "T", Slug: "s", Content: long}}); !utf8.ValidString(got) {
		t.Fatalf("FormatForPrompt returns invalid UTF-8")
	}
	if got := deriveTitle(long); !utf8.ValidString(got) || utf8.RuneCountInString(got) > 80 {
		t.Fatalf("deriveTitle: invalid UTF-8 or too long: %d runes", utf8.RuneCountInString(got))
	}
}

func TestExtractLinks(t *testing.T) {
	body := "Kunde ACME, betreut von [[Kollegin Zabel]]. Siehe auch [[projekt-x]] und " +
		"[[Kollegin Zabel]] (Dublette) sowie [[Ticket 42|das Login-Ticket]]."
	got := extractLinks(body)
	want := []string{"kollegin-zabel", "projekt-x", "ticket-42"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("extractLinks = %v, want %v", got, want)
	}
	if got := extractLinks("keine links hier"); len(got) != 0 {
		t.Fatalf("without links → empty, got %v", got)
	}
}

func TestSlugify(t *testing.T) {
	cases := map[string]string{
		"Kunde ACME":            "kunde-acme",
		"Über/Löschung & Ärger": "ueber-loeschung-aerger",
		"   ":                   "seite",
		"Ticket #42!":           "ticket-42",
	}
	for in, want := range cases {
		if got := slugify(in); got != want {
			t.Errorf("slugify(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestFormatIndexForPrompt(t *testing.T) {
	if got := FormatIndexForPrompt(nil); got != "" {
		t.Fatalf("empty index → empty string, got %q", got)
	}
	got := FormatIndexForPrompt([]Entry{
		{Slug: "kunde-acme", Title: "Kunde ACME"},
		{Slug: "projekt-x", Title: "Projekt X"},
	})
	// Slugs only, one line: the index is paid for on every turn, and the slug
	// carries the title (it is derived from it) as well as being what wiki_read
	// needs. What must not fall away is the coverage — every page belongs in it.
	for _, want := range []string{"Your wiki (index)", "[[kunde-acme]]", "[[projekt-x]]"} {
		if !strings.Contains(got, want) {
			t.Fatalf("index does not contain %q: %q", want, got)
		}
	}
	if strings.Contains(got, "Kunde ACME") {
		t.Fatalf("titles are redundant next to the slug and cost tokens per turn: %q", got)
	}
	lines := strings.Split(strings.TrimSpace(got), "\n")
	if last := lines[len(lines)-1]; last != "[[kunde-acme]] [[projekt-x]]" {
		t.Fatalf("the page list belongs on ONE line, got %q", last)
	}
}

func TestUnionSlugs(t *testing.T) {
	got := unionSlugs([]string{"a", "b"}, []string{"b", "c"}, nil, []string{"", "c", "d"})
	want := []string{"a", "b", "c", "d"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("unionSlugs = %v, want %v (dedup, order, no empty string)", got, want)
	}
	if got := unionSlugs(); len(got) != 0 {
		t.Fatalf("without input → empty (not a nil panic), got %v", got)
	}
}

func TestDeriveTitle(t *testing.T) {
	if got := deriveTitle("Kunde ACME reagiert nur telefonisch. Rest egal."); got != "Kunde ACME reagiert nur telefonisch" {
		t.Fatalf("deriveTitle sentence boundary: %q", got)
	}
	long := "Dies ist ein sehr langer Satz ohne Satzzeichen der weit über achtzig Zeichen hinausgeht und gekürzt werden muss"
	if got := deriveTitle(long); utf8.RuneCountInString(got) > 80 {
		t.Fatalf("deriveTitle must truncate to 80 characters, got %d: %q", utf8.RuneCountInString(got), got)
	}
	// A dot inside a domain must not chop the title down to a one-word fragment.
	if got := deriveTitle("x.educa-portal.de ist ein LMS-Demo-System der Digital Learning GmbH. Rest egal."); got != "x.educa-portal.de ist ein LMS-Demo-System der Digital Learning GmbH" {
		t.Fatalf("deriveTitle domain dot: %q", got)
	}
	// An abbreviation with a letter in front of the dot does not break it either.
	if got := deriveTitle("Antwort z.B. per Mail geht schneller als telefonisch. Ende."); got != "Antwort z.B. per Mail geht schneller als telefonisch" {
		t.Fatalf("deriveTitle abbreviation: %q", got)
	}
	// The spaced-out abbreviation "z. B." is no sentence end either — on the real
	// corpus it produced the title "Zugesagte Rückmeldungen (z".
	got := deriveTitle("Zugesagte Rückmeldungen (z. B. 'ich melde mich') erst nach Prüfung ins Wiki schreiben.")
	if strings.HasSuffix(got, "(z") {
		t.Fatalf("cut off at the abbreviation: %q", got)
	}
	if !strings.HasPrefix(got, "Zugesagte Rückmeldungen (z. B.") {
		t.Fatalf("deriveTitle spaced-out abbreviation: %q", got)
	}
}

// TestIsEpisodicTitle: the "diary title" finding hangs off deriveTitle's
// truncation limit — a title that reaches it is a cut-off sentence. Examples
// taken from the real corpus.
func TestIsEpisodicTitle(t *testing.T) {
	episodic := []string{
		// Capped at 80 characters → auto-generated by construction.
		"educa-ai-web (148), Stand 30.07.2026 11:00 UTC: alpha hat neue Deps und der Buil",
		"CI-Muster: MR-Pipelines von brunhilde.tatkraeftig in educa/educa laufen erst nach",
		// A full date names an event, not a thing.
		"Umstellung am 12.03.2026",
	}
	for _, s := range episodic {
		if !isEpisodicTitle(s) {
			t.Errorf("should count as a diary title (%d characters): %q", utf8.RuneCountInString(s), s)
		}
	}
	// Usable names must NOT trigger — a finding that flags almost everything no
	// longer tells anybody where to intervene.
	fine := []string{
		"Kunde ACME",
		"In educa lms ist der Hauptbranch educa-x-bugfix",
		"educa-ai-web (148): Review-/Merge-Wege meiner MRs",
		"Sandbox: PHP 8.2 existing — Laravel-Queries ohne das educa-Repo pruefen",
		// Version numbers are not dates.
		"gpt_markdown 1.1.8: Emphase-Opener-Guard ist verdreht",
	}
	for _, s := range fine {
		if isEpisodicTitle(s) {
			t.Errorf("not a diary title (%d characters): %q", utf8.RuneCountInString(s), s)
		}
	}
}
