-- Die Traumerzählung: zwei, drei Sätze darüber, wovon der Agent geträumt hat,
-- passend zu dem, was er tatsächlich am Gedächtnis geändert hat.
--
-- Bewusst Zierrat, und bewusst getrennt von den Handlungen: dream_actions ist
-- das Protokoll und die Wahrheit — wer wissen will, was passiert ist, liest
-- dort. Die Erzählung ist die Zusammenfassung, die jemand freiwillig liest.
-- Sie steht in der UI abgesetzt und darf nie an die Stelle des Protokolls
-- treten.
--
-- Leer, wenn ein Traum nichts getan hat: eine erfundene Geschichte über eine
-- Nacht, in der nichts geschah, wäre genau die Sorte Text, die man einmal
-- amüsant und danach nur noch lästig findet.
ALTER TABLE dreams ADD COLUMN story TEXT NOT NULL DEFAULT '';
