-- The dream story: two, three sentences about what the agent dreamed of,
-- matching what it actually changed in memory.
--
-- Deliberate ornament, and deliberately separate from the actions:
-- dream_actions is the record and the truth — whoever wants to know what
-- happened reads it there. The story is the summary somebody reads
-- voluntarily. It stands set apart in the UI and must never take the place
-- of the record.
--
-- Empty when a dream did nothing: an invented story about a night in which
-- nothing happened is exactly the kind of text somebody finds amusing once
-- and afterwards only annoying.
ALTER TABLE dreams ADD COLUMN story TEXT NOT NULL DEFAULT '';
