-- What does this organisation actually do.
--
-- Three to five sentences, asked in setup and editable afterwards under
-- organisations. Deliberately master data and not a setup prompt: the same
-- sentences answer the same question in several places — in the config of
-- newly drafted agents, in every requisition to the HR department and in the
-- system prompt of the config copilot, which so far knows the agent, its
-- target systems and its guard rails, but not the company it writes
-- for. Said once instead of repeated in every prompt.
--
-- spec/20-hiring-and-setup.md, spec/09-enterprise-model.md.
ALTER TABLE organizations ADD COLUMN description TEXT NOT NULL DEFAULT '';
