-- How many times in a row this task has lost its sandbox.
--
-- When the daemon connection breaks mid-run (Docker under resource pressure, a
-- network blip, a killed container), that is an infrastructure event and no
-- verdict on the agent's work — so the task is requeued instead of being set
-- to failed terminally.
--
-- For a *sporadic* abort that is right. For a *reproducible* one it is not:
-- broken sandbox image after a deploy, OOM at container start, an agent config
-- that reliably breaks the container. The loop then runs open -> ClaimNext ->
-- sandbox dies -> open forever, every round with a full sandbox start, and
-- nothing in the system shows that something here is stuck instead of
-- working.
--
-- This counter is the ceiling against that. It sits on the TASK and not in
-- process memory, because a restart of the control plane is one of the cases
-- that trigger the aborts: an in-memory counter would be back at zero after it
-- and the loop would keep running.
--
-- It resets as soon as a run ends for a DIFFERENT reason than the connection
-- break (reopen after budget stop, block, manual retry) — otherwise a
-- long-lived task would fail over weeks on accumulated single blips instead of
-- on a real series. "In a row" is the point.
--
-- No index: the column is only read together with the row the dispatcher
-- already has in hand anyway.
ALTER TABLE backlog_tasks
    ADD COLUMN daemon_retries INT NOT NULL DEFAULT 0;
